POST http://localhost:3000/api/heroes HTTP/1.1
Content-Type: application/json

{
  "nickname": "Cucu5",
  "realName": "Lala5",
  "originDesc": "Miami",
  "catchPhrase": "I'm a Cucu 1!",
  "powers": ["fly", "hover"]
}