POST http://localhost:3000/api/heroes HTTP/1.1
Content-Type: application/json

{
  "nickname": "Cucu10",
  "realName": "Lala2",
  "originDesc": "Miami",
  "catchPhrase": "I'm a Cucu!",
  "powers": "fly"
}